### PR TITLE
Adding Orlando to the hometown files

### PR DESCRIPTION
**Pull request by githubteacher**
This Pull Request was created to add the Orlando file to the class repo. I'll merge this when I have one 👍 

Some questions I'd ❤️ answered:
1. If you've been to Orlando, what did you like? What did you not like?
2. If you have kids, what kinds of attractions do they like?
3. What kind of food do people expect in Orlando?
4. @brianamarie would you be interested in any 🎶 activities in Orlando? Or is Chicago wayyyy better for that?

### CODE REVIEW

**Comment by brianamarie** [comment]
> What kind of food do people expect in Orlando?

Tacos! And whatever you like. 

> @brianamarie would you be interested in any 🎶 activities in Orlando? Or is Chicago wayyyy better for that?

@githubteacher I'm always down for 🎶 activities! Are there any symphonies or orchestras nearby? 🎻

**Comment by prdatta-intel** [comment]
this is my comment :+1:

**Comment by hectorsector** [comment]
@githubteacher for tacos I recommend **Rocco's Tacos**. A great place for 🎶 is the **Walt Disney Amphitheater in Downtown Orlando** and the **Dr. Philips Center for the Performing Arts**

**Comment by hectorsector** [comment]
🚢 it @githubteacher

**Pull request merged**
